- name: play variables
  hosts: localhost
  vars:
    url: play.example.com
  tasks:
    - name: print variables from play
      ansible.builtin.debug:
        msg: URL = {{ url }}

- name: play variables from files
  hosts: localhost
  vars_files:
    - vars.yml
  tasks:
    - name: print variables from files
      ansible.builtin.debug:
        msg: URL = {{ url }}

