#variables from play
- name: play variables
  hosts: localhost
  vars:
    url: play.example.com
  tasks:
    - name: print variables from play
      ansible.builtin.debug:
        msg: URL = {{ url }}

#variables from files
- name: play variables from files
  hosts: localhost
  vars_files:
    - vars.yml
  tasks:
    - name: print variables from files
      ansible.builtin.debug:
        msg: URL = {{ url }}

#variables from tasks
- name: play variables from tasks
  hosts: localhost
  tasks:
    - name: print variables from tasks
      vars: ##This variable works on this tasks only, tasks from same play cannot access this variable
        url: tasks.example.com
      ansible.builtin.debug:
        msg: URL = {{ url }}

#variables from inventory
- name: play variables from inventory
  hosts: localhost
  tasks:
    - name: print variables from inventory
      ansible.builtin.debug:
        msg: URL = {{ url }}

